name: Sync Fork

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: tgymnich/fork-sync@v1.8
        with:
          owner: revenge-mod
          repo: revenge-bundle-next
          base: main
          head: main
